### ISSUE TITLE
When using CMAC-AES and signing a Unicode object, an error occurs...

### ISSUE THREAD

**Issue by al-the-x** [doegox/python-cryptoplus#2]
Caveat: I'm not a crypto expert; I know enough to be dangerous. 

I'm attempting to use `CryptoPlus.Cipher.AES` to generate a CMAC-AES signature for an OAuth 1.0A Provider implementation. The message is a Unicode object containing a URL-encoded value; the key is a Unicode in hexadecimal format; the resulting cipher is to be base-64 encoded.

``` python
    from CryptoPlus.Cipher import AES

    def sign_cmac_aes(base_string, consumer_secret):
        key, message = consumer_secret.decode('hex'), base_string.decode('utf-8')

        return AES.new(key, AES.MODE_CMAC).encrypt(message).encode('base64')
```

The resulting signatures don't match the expected value. Considering the problems this Provider has in general, I'm not overly surprised, but I wanted to get another pair of eyes, perhaps with more experience with the CMAC-AES method being employed. Any thoughts?

**Comment by al-the-x** [comment]
The support staff on the Provider's end supplied an implementation that the claim works with the latest (alpha) build of PyCrypto:

``` python
    def encrypt_with_cmac(clear_text,private_key): 
        cmac_provider = CMAC.new(private_key,ciphermod=AES)

        cmac_provider.update(clear_text)

        encrypted = base64.b64encode(cmac_provider.digest())

        return encrypted
```

**Comment by doegox** [comment]
I assume you're talking about https://stackoverflow.com/questions/21464079/cmac-aes-in-python

I don't see any difference between "our" CMAC and "theirs":

```
>>> from CryptoPlus.Cipher import AES
>>> key = '2b7e151628aed2a6abf7158809cf4f3c'.decode('hex')
>>> plaintext = '6bc1bee22e409f96e93d7e117393172a'.decode('hex')
>>> cipher = AES.new(key,AES.MODE_CMAC)
>>> cipher.encrypt(plaintext).encode('hex')
'070a16b46b4d4144f79bdd9dd04a287c'
```

```
>>> from Crypto.Hash import CMAC
>>> from Crypto.Cipher import AES
>>> key = '2b7e151628aed2a6abf7158809cf4f3c'.decode('hex')
>>> plaintext = '6bc1bee22e409f96e93d7e117393172a'.decode('hex')
>>> cipher = CMAC.new(key, ciphermod=AES)
>>> cipher.update(plaintext)
>>> cipher.hexdigest()
'070a16b46b4d4144f79bdd9dd04a287c'
```

**Comment by al-the-x** [comment]
Yes, that's not mine, but it's the same provider. I figured out what they
were doing that was funky. Thanks for the verification.

David Rogers
http://about.me/al_the_x

Need help now? Schedule a call on Clarity.fm http://clarity.fm/althex

> > http://clarity.fm/althex
