### ISSUE TITLE
ImportError: No module named 'Crypto.Hash._MD2'

### ISSUE THREAD

**Issue by adombeck** [doegox/python-cryptoplus#7]
When importing `CryptoPlus.Hash`, I get this ImportError: `ImportError: No module named 'Crypto.Hash._MD2'`. My pycrypto version is 2.6.1 (more specifically: 2.6.1-4ubuntu0.2 in Ubuntu 14.04).

**Comment by adombeck** [comment]
And my Python version is 3.5.

**Comment by doegox** [comment]
CryptoPlus is a python2 module, not python3.
This must be an installation problem of pycrypto on your side.
I tested it with the setup you documented and I've no error:

```
docker run -it ubuntu:14.04
apt-get update
apt-get install python-crypto git python-setuptools
cd
git clone https://github.com/doegox/python-cryptoplus.git
cd python-cryptoplus/
python setup.py install
python -c "import CryptoPlus.Hash"
python -c "import Crypto.Hash._MD2"
dpkg -l|grep python-crypto
ii  python-crypto                   2.6.1-4ubuntu0.2                 amd64        cryptographic algorithms and protocols for Python
```
